# Generated by Django 2.2.1 on 2019-05-19 12:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('priority', models.IntegerField(blank=True, default=5, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expire_date', models.DateTimeField(null=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
